/*
 *  Copyright 2006 Edgardo Avilés López
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *    
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 * 
 ******************************************************************************/

package net.tinyos.tinysoa.common;

/*******************************************************************************
 * Parameter class which instances are provided by the services. It represents
 * a sensor type of the reading data generated by sensor nodes.
 * 
 * @author		Edgardo Avilés López
 * @version	0.1, 07/24/2006
 ******************************************************************************/
public class Parameter {
	
	private String name;
	private String description;
	
	/***************************************************************************
	 * Defines the name of the parameter.
	 * 
	 * @param name	The name for the parameter
	 **************************************************************************/
	public void setName(String name) {
		this.name = name;
	}
	
	/***************************************************************************
	 * Returns the name of the parameter.
	 * 
	 * @return	The name of the parameter
	 **************************************************************************/
	public String getName() {
		return name;
	}
	
	/***************************************************************************
	 * Defines the description of the parameter.
	 * 
	 * @param description	The description for the parameter
	 **************************************************************************/
	public void setDescription(String description) {
		this.description = description;
	}
	
	/***************************************************************************
	 * Returns the description of the parameter.
	 * 
	 * @return	Parameter The description of the parameter
	 **************************************************************************/
	public String getDescription() {
		return description;
	}
	
}
