/*
 *  Copyright 2006 Edgardo Avilés López
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *    
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 * 
 ******************************************************************************/

package net.tinyos.tinysoa.common;

/*******************************************************************************
 * Reading class which instances are provided by the services. It represents a
 * sensor reading generated by the sensor nodes. Each reading object consists of
 * the node ID from where the data is fetch, the date and dateTime when it was
 * received, and the sensor type and value.
 * 
 * @author		Edgardo Avilés López
 * @version	0.1, 07/24/2006
 ******************************************************************************/
public class Reading {
	
	private int nid;
	private String dateTime;
	private String parameter;
	private String value;
	
	/***************************************************************************
	 * Defines the ID of the node responsible of the reading.
	 * 
	 * @param nid	The ID of the node who generated the reading
	 **************************************************************************/
	public void setNid(int nid) {
		this.nid = nid;
	}
	
	/***************************************************************************
	 * Returns the ID of the node responsible of the reading.
	 * 
	 * @return	The ID of the node who generated the reading
	 **************************************************************************/
	public int getNid() {
		return nid;
	}
	
	/***************************************************************************
	 * Defines the date and dateTime in which the reading was received.
	 * 
	 * @param dateTime	The date and dateTime of reading reception
	 **************************************************************************/
	public void setDateTime(String dateTime) {
		this.dateTime = dateTime;
	}
	
	/***************************************************************************
	 * Returns the date and dateTime in which the reading was received.
	 * 
	 * @return	The date and dateTime of reading reception
	 **************************************************************************/
	public String getDateTime() {
		return dateTime;
	}
	
	/***************************************************************************
	 * Defines the sensor type of the reading.
	 * 
	 * @param parameter	The sensor type of the reading
	 **************************************************************************/
	public void setParameter(String parameter) {
		this.parameter = parameter;
	}
	
	/***************************************************************************
	 * Returns the sensor type of the reading.
	 * 
	 * @return	Reading The sensor type of the reading
	 **************************************************************************/
	public String getParameter() {
		return parameter;
	}
	
	/***************************************************************************
	 * Defines the sensor value of the reading.
	 * 
	 * @param value	The reading sensor value
	 **************************************************************************/
	public void setValue(String value) {
		this.value = value;
	}
	
	/***************************************************************************
	 * Returns the sensor value of the reading.
	 * 
	 * @return	The reading sensor value
	 **************************************************************************/
	public String getValue() {
		return value;
	}
	
	/***************************************************************************
	 * Returns a string with the reading object information.
	 * 
	 * @return	A string with the object information
	 **************************************************************************/
	public String toString() {
		return nid + ": " + dateTime + " (" + parameter + "=" + value + ")";
	}
	
}
