/*
 *  Copyright 2007 Edgardo Avilés López
 * 
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *    
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 * 
 ******************************************************************************/

package net.tinyos.tinysoa.common;

/*******************************************************************************
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'TinySOAMsg'
 * message type.
 * 
 * @author		Edgardo Avilés López
 * @version	0.3, 07/24/2006
 ******************************************************************************/

public class TinySOAMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 21;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 24;
    
    public static final int MY_OFFSET = 8 * 7;

    /** Create a new TinySOAMsg of size 21. */
    public TinySOAMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new TinySOAMsg of the given data_length. */
    public TinySOAMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TinySOAMsg with the given data_length
     * and base offset.
     */
    public TinySOAMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TinySOAMsg using the given byte array
     * as backing store.
     */
    public TinySOAMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TinySOAMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public TinySOAMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TinySOAMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public TinySOAMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TinySOAMsg embedded in the given message
     * at the given base offset.
     */
    public TinySOAMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new TinySOAMsg embedded in the given message
     * at the given base offset and length.
     */
    public TinySOAMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <TinySOAMsg> \n";
      try {
        s += "  [l1=0x"+Long.toHexString(get_l1())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [l2=0x"+Long.toHexString(get_l2())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [l3=0x"+Long.toHexString(get_l3())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [l4=0x"+Long.toHexString(get_l4())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [l5=0x"+Long.toHexString(get_l5())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [l6=0x"+Long.toHexString(get_l6())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [l7=0x"+Long.toHexString(get_l7())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [l8=0x"+Long.toHexString(get_l8())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [id=0x"+Long.toHexString(get_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [parent=0x"+Long.toHexString(get_parent())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [nsec=0x"+Long.toHexString(get_nseq())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [sensor=0x"+Long.toHexString(get_sensor())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [type=0x"+Long.toHexString(get_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: l1
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'l1' is signed (false).
     */
    public static boolean isSigned_l1() {
        return false;
    }

    /**
     * Return whether the field 'l1' is an array (false).
     */
    public static boolean isArray_l1() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'l1'
     */
    public static int offset_l1() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'l1'
     */
    public static int offsetBits_l1() {
        return 0 + MY_OFFSET;
    }

    /**
     * Return the value (as a int) of the field 'l1'
     */
    public int get_l1() {
        return (int)getUIntElement(offsetBits_l1(), 16);
    }

    /**
     * Set the value of the field 'l1'
     */
    public void set_l1(int value) {
        setUIntElement(offsetBits_l1(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'l1'
     */
    public static int size_l1() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'l1'
     */
    public static int sizeBits_l1() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: l2
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'l2' is signed (false).
     */
    public static boolean isSigned_l2() {
        return false;
    }

    /**
     * Return whether the field 'l2' is an array (false).
     */
    public static boolean isArray_l2() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'l2'
     */
    public static int offset_l2() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'l2'
     */
    public static int offsetBits_l2() {
        return 16 + MY_OFFSET;
    }

    /**
     * Return the value (as a int) of the field 'l2'
     */
    public int get_l2() {
        return (int)getUIntElement(offsetBits_l2(), 16);
    }

    /**
     * Set the value of the field 'l2'
     */
    public void set_l2(int value) {
        setUIntElement(offsetBits_l2(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'l2'
     */
    public static int size_l2() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'l2'
     */
    public static int sizeBits_l2() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: l3
    //   Field type: int, unsigned
    //   Offset (bits): 32
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'l3' is signed (false).
     */
    public static boolean isSigned_l3() {
        return false;
    }

    /**
     * Return whether the field 'l3' is an array (false).
     */
    public static boolean isArray_l3() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'l3'
     */
    public static int offset_l3() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'l3'
     */
    public static int offsetBits_l3() {
        return 32 + MY_OFFSET;
    }

    /**
     * Return the value (as a int) of the field 'l3'
     */
    public int get_l3() {
        return (int)getUIntElement(offsetBits_l3(), 16);
    }

    /**
     * Set the value of the field 'l3'
     */
    public void set_l3(int value) {
        setUIntElement(offsetBits_l3(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'l3'
     */
    public static int size_l3() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'l3'
     */
    public static int sizeBits_l3() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: l4
    //   Field type: int, unsigned
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'l4' is signed (false).
     */
    public static boolean isSigned_l4() {
        return false;
    }

    /**
     * Return whether the field 'l4' is an array (false).
     */
    public static boolean isArray_l4() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'l4'
     */
    public static int offset_l4() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'l4'
     */
    public static int offsetBits_l4() {
        return 48 + MY_OFFSET;
    }

    /**
     * Return the value (as a int) of the field 'l4'
     */
    public int get_l4() {
        return (int)getUIntElement(offsetBits_l4(), 16);
    }

    /**
     * Set the value of the field 'l4'
     */
    public void set_l4(int value) {
        setUIntElement(offsetBits_l4(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'l4'
     */
    public static int size_l4() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'l4'
     */
    public static int sizeBits_l4() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: l5
    //   Field type: int, unsigned
    //   Offset (bits): 64
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'l5' is signed (false).
     */
    public static boolean isSigned_l5() {
        return false;
    }

    /**
     * Return whether the field 'l5' is an array (false).
     */
    public static boolean isArray_l5() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'l5'
     */
    public static int offset_l5() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'l5'
     */
    public static int offsetBits_l5() {
        return 64 + MY_OFFSET;
    }

    /**
     * Return the value (as a int) of the field 'l5'
     */
    public int get_l5() {
        return (int)getUIntElement(offsetBits_l5(), 16);
    }

    /**
     * Set the value of the field 'l5'
     */
    public void set_l5(int value) {
        setUIntElement(offsetBits_l5(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'l5'
     */
    public static int size_l5() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'l5'
     */
    public static int sizeBits_l5() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: l6
    //   Field type: int, unsigned
    //   Offset (bits): 80
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'l6' is signed (false).
     */
    public static boolean isSigned_l6() {
        return false;
    }

    /**
     * Return whether the field 'l6' is an array (false).
     */
    public static boolean isArray_l6() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'l6'
     */
    public static int offset_l6() {
        return (80 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'l6'
     */
    public static int offsetBits_l6() {
        return 80 + MY_OFFSET;
    }

    /**
     * Return the value (as a int) of the field 'l6'
     */
    public int get_l6() {
        return (int)getUIntElement(offsetBits_l6(), 16);
    }

    /**
     * Set the value of the field 'l6'
     */
    public void set_l6(int value) {
        setUIntElement(offsetBits_l6(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'l6'
     */
    public static int size_l6() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'l6'
     */
    public static int sizeBits_l6() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: l7
    //   Field type: int, unsigned
    //   Offset (bits): 96
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'l7' is signed (false).
     */
    public static boolean isSigned_l7() {
        return false;
    }

    /**
     * Return whether the field 'l7' is an array (false).
     */
    public static boolean isArray_l7() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'l7'
     */
    public static int offset_l7() {
        return (96 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'l7'
     */
    public static int offsetBits_l7() {
        return 96 + MY_OFFSET;
    }

    /**
     * Return the value (as a int) of the field 'l7'
     */
    public int get_l7() {
        return (int)getUIntElement(offsetBits_l7(), 16);
    }

    /**
     * Set the value of the field 'l7'
     */
    public void set_l7(int value) {
        setUIntElement(offsetBits_l7(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'l7'
     */
    public static int size_l7() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'l7'
     */
    public static int sizeBits_l7() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: l8
    //   Field type: int, unsigned
    //   Offset (bits): 112
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'l8' is signed (false).
     */
    public static boolean isSigned_l8() {
        return false;
    }

    /**
     * Return whether the field 'l8' is an array (false).
     */
    public static boolean isArray_l8() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'l8'
     */
    public static int offset_l8() {
        return (112 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'l8'
     */
    public static int offsetBits_l8() {
        return 112 + MY_OFFSET;
    }

    /**
     * Return the value (as a int) of the field 'l8'
     */
    public int get_l8() {
        return (int)getUIntElement(offsetBits_l8(), 16);
    }

    /**
     * Set the value of the field 'l8'
     */
    public void set_l8(int value) {
        setUIntElement(offsetBits_l8(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'l8'
     */
    public static int size_l8() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'l8'
     */
    public static int sizeBits_l8() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: id
    //   Field type: short, unsigned
    //   Offset (bits): 128
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'id' is signed (false).
     */
    public static boolean isSigned_id() {
        return false;
    }

    /**
     * Return whether the field 'id' is an array (false).
     */
    public static boolean isArray_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'id'
     */
    public static int offset_id() {
        return (128 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'id'
     */
    public static int offsetBits_id() {
        return 128 + MY_OFFSET;
    }

    /**
     * Return the value (as a short) of the field 'id'
     */
    public short get_id() {
        return (short)getUIntElement(offsetBits_id(), 8);
    }

    /**
     * Set the value of the field 'id'
     */
    public void set_id(short value) {
        setUIntElement(offsetBits_id(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'id'
     */
    public static int size_id() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'id'
     */
    public static int sizeBits_id() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: parent
    //   Field type: short, unsigned
    //   Offset (bits): 136
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'parent' is signed (false).
     */
    public static boolean isSigned_parent() {
        return false;
    }

    /**
     * Return whether the field 'parent' is an array (false).
     */
    public static boolean isArray_parent() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'parent'
     */
    public static int offset_parent() {
        return (136 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'parent'
     */
    public static int offsetBits_parent() {
        return 136 + MY_OFFSET;
    }

    /**
     * Return the value (as a short) of the field 'parent'
     */
    public short get_parent() {
        return (short)getUIntElement(offsetBits_parent(), 8);
    }

    /**
     * Set the value of the field 'parent'
     */
    public void set_parent(short value) {
        setUIntElement(offsetBits_parent(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'parent'
     */
    public static int size_parent() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'parent'
     */
    public static int sizeBits_parent() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: nsec
    //   Field type: short, unsigned
    //   Offset (bits): 144
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'nsec' is signed (false).
     */
    public static boolean isSigned_nseq() {
        return false;
    }

    /**
     * Return whether the field 'nsec' is an array (false).
     */
    public static boolean isArray_nseq() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'nsec'
     */
    public static int offset_nseq() {
        return (144 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'nsec'
     */
    public static int offsetBits_nseq() {
        return 144 + MY_OFFSET;
    }

    /**
     * Return the value (as a short) of the field 'nsec'
     */
    public short get_nseq() {
        return (short)getUIntElement(offsetBits_nseq(), 8);
    }

    /**
     * Set the value of the field 'nsec'
     */
    public void set_nseq(short value) {
        setUIntElement(offsetBits_nseq(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'nsec'
     */
    public static int size_nseq() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'nsec'
     */
    public static int sizeBits_nseq() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: sensor
    //   Field type: short, unsigned
    //   Offset (bits): 152
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'sensor' is signed (false).
     */
    public static boolean isSigned_sensor() {
        return false;
    }

    /**
     * Return whether the field 'sensor' is an array (false).
     */
    public static boolean isArray_sensor() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'sensor'
     */
    public static int offset_sensor() {
        return (152 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'sensor'
     */
    public static int offsetBits_sensor() {
        return 152 + MY_OFFSET;
    }

    /**
     * Return the value (as a short) of the field 'sensor'
     */
    public short get_sensor() {
        return (short)getUIntElement(offsetBits_sensor(), 8);
    }

    /**
     * Set the value of the field 'sensor'
     */
    public void set_sensor(short value) {
        setUIntElement(offsetBits_sensor(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'sensor'
     */
    public static int size_sensor() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'sensor'
     */
    public static int sizeBits_sensor() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: type
    //   Field type: short, unsigned
    //   Offset (bits): 160
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'type' is signed (false).
     */
    public static boolean isSigned_type() {
        return false;
    }

    /**
     * Return whether the field 'type' is an array (false).
     */
    public static boolean isArray_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'type'
     */
    public static int offset_type() {
        return (160 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'type'
     */
    public static int offsetBits_type() {
        return 160 + MY_OFFSET;
    }

    /**
     * Return the value (as a short) of the field 'type'
     */
    public short get_type() {
        return (short)getUIntElement(offsetBits_type(), 8);
    }

    /**
     * Set the value of the field 'type'
     */
    public void set_type(short value) {
        setUIntElement(offsetBits_type(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'type'
     */
    public static int size_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'type'
     */
    public static int sizeBits_type() {
        return 8;
    }

}
